import 'app_models.dart';

class DummyData {
  DummyData._();

  static final agent = AgentProfile(
    id: 'AGT001',
    name: 'Fredrick Morgan',
    phone: '+233 24 567 8901',
    email: 'f.morgan@soiltech.com',
    agentCode: 'LBC-ASH-001',
    region: 'Ashanti Region',
    district: 'Kumasi Metro',
    avatarUrl: 'https://i.pravatar.cc/150?img=33',
    totalFarmersRegistered: 142,
    totalProduceCollected: 45680,
    totalCollections: 287,
    performanceScore: 94.5,
    joinDate: DateTime(2022, 3, 15),
  );

  static final stats = DashboardStats(
    todayCollections: 7,
    todayFarmers: 5,
    pendingUploads: 3,
    offlineRecords: 2,
    todayWeight: 1842.5,
    weeklyWeight: 12450.0,
    monthlyRevenue: 87340.0,
    activePickups: 4,
  );

  static final List<FarmerModel> farmers = [
    FarmerModel(
      id: 'FRM001',
      name: 'Kofi Mensah',
      phone: '+233 24 123 4567',
      nationalId: 'GHA-12345678-9',
      region: 'Ashanti Region',
      district: 'Ejisu-Juaben',
      community: 'Ejisu',
      avatarUrl: 'https://i.pravatar.cc/150?img=11',
      status: FarmerStatus.approved,
      registeredDate: DateTime(2023, 2, 14),
      totalFarms: 2,
      totalAcreage: 8.5,
      farms: [],
      crops: ['Cocoa', 'Plantain'],
      totalCollected: 12450.0,
      syncStatus: SyncStatus.synced,
    ),
    FarmerModel(
      id: 'FRM002',
      name: 'Akua Asante',
      phone: '+233 20 987 6543',
      nationalId: 'GHA-98765432-1',
      region: 'Ashanti Region',
      district: 'Kwabre East',
      community: 'Mamponteng',
      avatarUrl: 'https://i.pravatar.cc/150?img=5',
      status: FarmerStatus.approved,
      registeredDate: DateTime(2023, 5, 22),
      totalFarms: 3,
      totalAcreage: 12.0,
      farms: [],
      crops: ['Cocoa', 'Maize', 'Cassava'],
      totalCollected: 18920.0,
      syncStatus: SyncStatus.synced,
    ),
    FarmerModel(
      id: 'FRM003',
      name: 'Yaw Boateng',
      phone: '+233 50 234 5678',
      nationalId: 'GHA-23456789-3',
      region: 'Ashanti Region',
      district: 'Afigya Kwabre',
      community: 'Kuntanase',
      avatarUrl: 'https://i.pravatar.cc/150?img=15',
      status: FarmerStatus.approved,
      registeredDate: DateTime(2023, 8, 10),
      totalFarms: 1,
      totalAcreage: 5.0,
      farms: [],
      crops: ['Maize', 'Yam'],
      totalCollected: 7230.0,
      syncStatus: SyncStatus.pending,
    ),
    FarmerModel(
      id: 'FRM004',
      name: 'Abena Owusu',
      phone: '+233 26 345 6789',
      nationalId: 'GHA-34567890-5',
      region: 'Ashanti Region',
      district: 'Bosomtwe',
      community: 'Bonwire',
      avatarUrl: 'https://i.pravatar.cc/150?img=9',
      status: FarmerStatus.approved,
      registeredDate: DateTime(2024, 1, 5),
      totalFarms: 2,
      totalAcreage: 9.5,
      farms: [],
      crops: ['Cocoa', 'Cassava'],
      totalCollected: 9870.0,
      syncStatus: SyncStatus.synced,
    ),
    FarmerModel(
      id: 'FRM005',
      name: 'Kwame Acheampong',
      phone: '+233 55 456 7890',
      nationalId: 'GHA-45678901-7',
      region: 'Ashanti Region',
      district: 'Sekyere East',
      community: 'Effiduase',
      avatarUrl: 'https://i.pravatar.cc/150?img=22',
      status: FarmerStatus.pending,
      registeredDate: DateTime(2022, 11, 30),
      totalFarms: 4,
      totalAcreage: 18.0,
      farms: [],
      crops: ['Cocoa', 'Rice', 'Maize'],
      totalCollected: 31450.0,
      syncStatus: SyncStatus.synced,
    ),
    FarmerModel(
      id: 'FRM006',
      name: 'Ama Serwaa',
      phone: '+233 27 567 8901',
      nationalId: 'GHA-56789012-9',
      region: 'Ashanti Region',
      district: 'Mampong Municipal',
      community: 'Mampong',
      avatarUrl: 'https://i.pravatar.cc/150?img=3',
      status: FarmerStatus.approved,
      registeredDate: DateTime(2024, 3, 18),
      totalFarms: 1,
      totalAcreage: 3.5,
      farms: [],
      crops: ['Tomato', 'Pepper'],
      totalCollected: 4120.0,
      syncStatus: SyncStatus.failed,
    ),
    FarmerModel(
      id: 'FRM007',
      name: 'Kwasi Frimpong',
      phone: '+233 24 678 9012',
      nationalId: 'GHA-67890123-1',
      region: 'Ashanti Region',
      district: 'Atwima Nwabiagya',
      community: 'Barekese',
      avatarUrl: 'https://i.pravatar.cc/150?img=19',
      status: FarmerStatus.approved,
      registeredDate: DateTime(2023, 6, 25),
      totalFarms: 2,
      totalAcreage: 7.0,
      farms: [],
      crops: ['Cocoa', 'Plantain'],
      totalCollected: 11340.0,
      syncStatus: SyncStatus.synced,
    ),
  ];

  static List<ProduceRecord> get produceRecords => [
    ProduceRecord(
      id: 'PRD001',
      farmerId: 'FRM001',
      farmerName: 'Kofi Mensah',
      farmId: 'FAR001',
      cropType: 'Cocoa',
      weightKg: 420.5,
      quantityBags: 7,
      moisturePercent: 7.2,
      qualityGrade: 'Grade A',
      status: CollectionStatus.approved,
      collectionDate: DateTime.now().subtract(const Duration(hours: 2)),
      photoUrls: [],
      agentId: 'AGT001',
      notes: 'Excellent quality beans, well fermented.',
      pricePerKg: 16.50,
      syncStatus: SyncStatus.synced,
    ),
    ProduceRecord(
      id: 'PRD002',
      farmerId: 'FRM002',
      farmerName: 'Akua Asante',
      farmId: 'FAR002',
      cropType: 'Cocoa',
      weightKg: 285.0,
      quantityBags: 5,
      moisturePercent: 8.1,
      qualityGrade: 'Grade A',
      status: CollectionStatus.submitted,
      collectionDate: DateTime.now().subtract(const Duration(hours: 4)),
      photoUrls: [],
      agentId: 'AGT001',
      notes: 'Good quality, minor moisture concern.',
      pricePerKg: 16.50,
      syncStatus: SyncStatus.synced,
    ),
    ProduceRecord(
      id: 'PRD003',
      farmerId: 'FRM003',
      farmerName: 'Yaw Boateng',
      farmId: 'FAR003',
      cropType: 'Maize',
      weightKg: 650.0,
      quantityBags: 13,
      moisturePercent: 12.5,
      qualityGrade: 'Grade B',
      status: CollectionStatus.draft,
      collectionDate: DateTime.now().subtract(const Duration(hours: 6)),
      photoUrls: [],
      agentId: 'AGT001',
      notes: 'Pending quality verification.',
      pricePerKg: 3.20,
      syncStatus: SyncStatus.pending,
    ),
    ProduceRecord(
      id: 'PRD004',
      farmerId: 'FRM004',
      farmerName: 'Abena Owusu',
      farmId: 'FAR004',
      cropType: 'Cocoa',
      weightKg: 187.5,
      quantityBags: 3,
      moisturePercent: 6.8,
      qualityGrade: 'Grade A',
      status: CollectionStatus.approved,
      collectionDate: DateTime.now().subtract(const Duration(days: 1)),
      photoUrls: [],
      agentId: 'AGT001',
      notes: 'Premium quality.',
      pricePerKg: 16.50,
      syncStatus: SyncStatus.synced,
    ),
    ProduceRecord(
      id: 'PRD005',
      farmerId: 'FRM005',
      farmerName: 'Kwame Acheampong',
      farmId: 'FAR005',
      cropType: 'Rice',
      weightKg: 900.0,
      quantityBags: 18,
      moisturePercent: 14.0,
      qualityGrade: 'Grade B',
      status: CollectionStatus.submitted,
      collectionDate: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
      photoUrls: [],
      agentId: 'AGT001',
      notes: 'Standard grade, good for processing.',
      pricePerKg: 4.80,
      syncStatus: SyncStatus.synced,
    ),
  ];

  static List<PickupRequest> get pickupRequests => [
    PickupRequest(
      id: 'PKP001',
      produceRecordId: 'PRD001',
      farmerId: 'FRM001',
      farmerName: 'Kofi Mensah',
      cropType: 'Cocoa',
      weightKg: 420.5,
      pickupLocation: 'Ejisu Junction, Kumasi',
      pickupLatitude: 6.7157,
      pickupLongitude: -1.4753,
      deliveryLocation: 'SoilTech Warehouse, Kumasi',
      status: LogisticsStatus.inTransit,
      requestDate: DateTime.now().subtract(const Duration(hours: 3)),
      driverName: 'Emmanuel Darko',
      driverPhone: '+233 24 111 2222',
      vehicleNumber: 'AS-3456-22',
      estimatedPickup: DateTime.now().add(const Duration(minutes: 45)),
      syncStatus: SyncStatus.synced,
    ),
    PickupRequest(
      id: 'PKP002',
      produceRecordId: 'PRD002',
      farmerId: 'FRM002',
      farmerName: 'Akua Asante',
      cropType: 'Cocoa',
      weightKg: 285.0,
      pickupLocation: 'Mamponteng Main Road',
      pickupLatitude: 6.7502,
      pickupLongitude: -1.5321,
      deliveryLocation: 'SoilTech Warehouse, Kumasi',
      status: LogisticsStatus.assigned,
      requestDate: DateTime.now().subtract(const Duration(hours: 1)),
      driverName: 'Samuel Asare',
      driverPhone: '+233 20 333 4444',
      vehicleNumber: 'AS-7891-21',
      estimatedPickup: DateTime.now().add(const Duration(hours: 2)),
      syncStatus: SyncStatus.synced,
    ),
    PickupRequest(
      id: 'PKP003',
      produceRecordId: 'PRD003',
      farmerId: 'FRM003',
      farmerName: 'Yaw Boateng',
      cropType: 'Maize',
      weightKg: 650.0,
      pickupLocation: 'Kuntanase Village',
      pickupLatitude: 6.8012,
      pickupLongitude: -1.6123,
      deliveryLocation: 'SoilTech Depot, Ejisu',
      status: LogisticsStatus.pending,
      requestDate: DateTime.now().subtract(const Duration(minutes: 30)),
      syncStatus: SyncStatus.pending,
    ),
    PickupRequest(
      id: 'PKP004',
      produceRecordId: 'PRD004',
      farmerId: 'FRM004',
      farmerName: 'Abena Owusu',
      cropType: 'Cocoa',
      weightKg: 187.5,
      pickupLocation: 'Bonwire Town Center',
      pickupLatitude: 6.7634,
      pickupLongitude: -1.4102,
      deliveryLocation: 'SoilTech Warehouse, Kumasi',
      status: LogisticsStatus.delivered,
      requestDate: DateTime.now().subtract(const Duration(days: 1)),
      driverName: 'Emmanuel Darko',
      driverPhone: '+233 24 111 2222',
      vehicleNumber: 'AS-3456-22',
      estimatedPickup: DateTime.now().subtract(const Duration(hours: 18)),
      syncStatus: SyncStatus.synced,
    ),
  ];

  static List<PaymentRecord> get payments => [
    PaymentRecord(
      id: 'PAY001',
      farmerId: 'FRM001',
      farmerName: 'Kofi Mensah',
      farmerPhone: '+233 24 123 4567',
      produceRecordId: 'PRD001',
      cropType: 'Cocoa',
      amount: 6938.25,
      status: PaymentStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 2)),
      paymentMethod: 'Mobile Money',
      syncStatus: SyncStatus.synced,
    ),
    PaymentRecord(
      id: 'PAY002',
      farmerId: 'FRM002',
      farmerName: 'Akua Asante',
      farmerPhone: '+233 20 987 6543',
      produceRecordId: 'PRD002',
      cropType: 'Cocoa',
      amount: 4702.50,
      status: PaymentStatus.processing,
      dueDate: DateTime.now().add(const Duration(days: 1)),
      paymentMethod: 'Bank Transfer',
      syncStatus: SyncStatus.synced,
    ),
    PaymentRecord(
      id: 'PAY003',
      farmerId: 'FRM004',
      farmerName: 'Abena Owusu',
      farmerPhone: '+233 26 345 6789',
      produceRecordId: 'PRD004',
      cropType: 'Cocoa',
      amount: 3093.75,
      status: PaymentStatus.paid,
      dueDate: DateTime.now().subtract(const Duration(days: 1)),
      paidDate: DateTime.now().subtract(const Duration(hours: 5)),
      paymentMethod: 'Mobile Money',
      transactionRef: 'MTN-2025-789456',
      syncStatus: SyncStatus.synced,
    ),
    PaymentRecord(
      id: 'PAY004',
      farmerId: 'FRM005',
      farmerName: 'Kwame Acheampong',
      farmerPhone: '+233 55 456 7890',
      produceRecordId: 'PRD005',
      cropType: 'Rice',
      amount: 4320.00,
      status: PaymentStatus.paid,
      dueDate: DateTime.now().subtract(const Duration(days: 2)),
      paidDate: DateTime.now().subtract(const Duration(days: 1)),
      paymentMethod: 'Bank Transfer',
      transactionRef: 'GCB-2025-123789',
      syncStatus: SyncStatus.synced,
    ),
  ];

  static List<AppNotification> get notifications => [
    AppNotification(
      id: 'NOT001',
      title: 'New Price Update',
      body: 'Cocoa Grade A price has been updated to GHS 16.50/kg effective today.',
      type: NotificationType.announcement,
      timestamp: DateTime.now().subtract(const Duration(minutes: 30)),
      isRead: false,
      data: {'type': 'price_update', 'crop': 'Cocoa'},
    ),
    AppNotification(
      id: 'NOT002',
      title: 'Pickup Confirmed',
      body: 'Driver Emmanuel Darko has been assigned to collect from Kofi Mensah.',
      type: NotificationType.task,
      timestamp: DateTime.now().subtract(const Duration(hours: 1)),
      isRead: false,
      data: {'type': 'pickup', 'requestId': 'PKP001'},
    ),
    AppNotification(
      id: 'NOT003',
      title: 'Payment Processed',
      body: 'GHS 3,093.75 has been sent to Abena Owusu via Mobile Money.',
      type: NotificationType.payment,
      timestamp: DateTime.now().subtract(const Duration(hours: 5)),
      isRead: true,
      data: {'type': 'payment', 'paymentId': 'PAY003'},
    ),
    AppNotification(
      id: 'NOT004',
      title: 'Sync Reminder',
      body: 'You have 3 records pending upload. Connect to internet to sync.',
      type: NotificationType.sync,
      timestamp: DateTime.now().subtract(const Duration(hours: 8)),
      isRead: true,
      data: {'type': 'sync', 'count': 3},
    ),
    AppNotification(
      id: 'NOT005',
      title: 'Quality Alert',
      body: 'Record PRD003 needs moisture review before final approval.',
      type: NotificationType.alert,
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      isRead: true,
      data: {'type': 'quality', 'recordId': 'PRD003'},
    ),
    AppNotification(
      id: 'NOT006',
      title: 'Monthly Target Update',
      body: 'You have reached 87% of your monthly collection target. Great work!',
      type: NotificationType.announcement,
      timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 4)),
      isRead: true,
      data: {'type': 'target', 'percent': 87},
    ),
  ];

  static List<Map<String, dynamic>> get weeklyChartData => [
    {'day': 'Mon', 'kg': 1850.0},
    {'day': 'Tue', 'kg': 2340.0},
    {'day': 'Wed', 'kg': 980.0},
    {'day': 'Thu', 'kg': 3120.0},
    {'day': 'Fri', 'kg': 1650.0},
    {'day': 'Sat', 'kg': 2890.0},
    {'day': 'Sun', 'kg': 1620.0},
  ];

  static List<Map<String, dynamic>> get cropDistribution => [
    {'crop': 'Cocoa', 'percent': 0.65, 'kg': 29692.0},
    {'crop': 'Maize', 'percent': 0.15, 'kg': 6852.0},
    {'crop': 'Cassava', 'percent': 0.10, 'kg': 4568.0},
    {'crop': 'Rice', 'percent': 0.07, 'kg': 3198.0},
    {'crop': 'Others', 'percent': 0.03, 'kg': 1370.0},
  ];

  static final List<Map<String, String>> recentActivities = [
    {
      'action': 'Collection recorded',
      'detail': 'Kofi Mensah – 420.5 kg Cocoa',
      'time': '2h ago',
      'icon': 'agriculture',
    },
    {
      'action': 'Farmer registered',
      'detail': 'Akua Asante – Kwabre East',
      'time': '4h ago',
      'icon': 'person_add',
    },
    {
      'action': 'Pickup requested',
      'detail': 'Yaw Boateng – 650 kg Maize',
      'time': '6h ago',
      'icon': 'local_shipping',
    },
    {
      'action': 'Payment sent',
      'detail': 'Abena Owusu – GHS 3,093.75',
      'time': '8h ago',
      'icon': 'payments',
    },
    {
      'action': 'Farm registered',
      'detail': 'Kwame Acheampong – 4.5 acres',
      'time': 'Yesterday',
      'icon': 'terrain',
    },
  ];

  // ─── Customer Data ───────────────────────────────────────────────────────────

  static final CustomerProfile dummyCustomer = CustomerProfile(
    id: 'CST001',
    fullName: 'Abena Osei',
    phone: '+233 55 123 4567',
    email: 'abena.osei@gmail.com',
    accountType: CustomerAccountType.individual,
    profileImageUrl: 'https://i.pravatar.cc/150?img=47',
    totalOrders: 14,
    addresses: const [
      DeliveryAddress(
        id: 'ADDR001',
        label: 'Home',
        fullAddress: '14 Liberation Road, Airport Area',
        city: 'Accra',
        region: 'Greater Accra',
        isDefault: true,
      ),
      DeliveryAddress(
        id: 'ADDR002',
        label: 'Office',
        fullAddress: 'Ridge Residences, Cantonments',
        city: 'Accra',
        region: 'Greater Accra',
        isDefault: false,
      ),
    ],
    createdAt: DateTime(2026, 3, 10),
  );

  static final List<Product> products = [
    Product(
      id: 'P001',
      name: 'Fresh Roma Tomatoes',
      description: 'Sun-ripened Roma tomatoes straight from Brong-Ahafo farms. Firm, juicy, and perfect for stews, sauces, and salads.',
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&q=80',
      galleryImages: [
        'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&q=80',
        'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=800&q=80',
      ],
      pricePerUnit: 18.0,
      unit: 'kg',
      stockQuantity: 500,
      farmerName: 'Kofi Mensah',
      location: 'Ejisu, Ashanti',
      averageRating: 4.7,
      reviewCount: 128,
      categoryId: 'dummy',
      freshnessLabel: 'Harvested Today',
      isFeatured: true,
      isAvailable: true,
    ),
    Product(
      id: 'P002',
      name: 'Scotch Bonnet Pepper',
      description: 'Premium scotch bonnet pepper, fiery and fragrant. Grown organically in the Volta region — the secret ingredient in authentic Ghanaian cuisine.',
      imageUrl: 'https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=400&q=80',
      galleryImages: ['https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=800&q=80'],
      pricePerUnit: 25.0,
      unit: 'kg',
      stockQuantity: 200,
      farmerName: 'Akua Asante',
      location: 'Mamponteng, Ashanti',
      averageRating: 4.9,
      reviewCount: 87,
      categoryId: 'dummy',
      freshnessLabel: 'Yesterday',
      isFeatured: true,
      isOnDeal: true,
      originalPrice: 32.0,
      isAvailable: true,
    ),
    Product(
      id: 'P003',
      name: 'Sweet White Onion',
      description: 'Large, sweet white onions from Northern Region farms. Mild flavour, ideal for raw use or cooking. Excellent shelf life.',
      imageUrl: 'https://images.unsplash.com/photo-1508747703725-719777637510?w=400&q=80',
      galleryImages: ['https://images.unsplash.com/photo-1508747703725-719777637510?w=800&q=80'],
      pricePerUnit: 12.0,
      unit: 'kg',
      stockQuantity: 1200,
      farmerName: 'Yaw Boateng',
      location: 'Agona Swedru, C/R',
      averageRating: 4.5,
      reviewCount: 210,
      categoryId: 'dummy',
      freshnessLabel: '3 days ago',
      isOnDeal: true,
      originalPrice: 15.0,
      isAvailable: true,
    ),
    Product(
      id: 'P004',
      name: 'Green Head Cabbage',
      description: 'Crisp, dense green cabbage heads, fresh from the highlands. Perfect for coleslaw, stir-fries, and traditional soups.',
      imageUrl: 'https://images.unsplash.com/photo-1594282418734-e5e4b33a76ed?w=400&q=80',
      galleryImages: ['https://images.unsplash.com/photo-1594282418734-e5e4b33a76ed?w=800&q=80'],
      pricePerUnit: 8.0,
      unit: 'head',
      stockQuantity: 350,
      farmerName: 'Abena Owusu',
      location: 'Bechem, B-A Region',
      averageRating: 4.3,
      reviewCount: 54,
      categoryId: 'dummy',
      freshnessLabel: '2 days ago',
      isAvailable: true,
    ),
    Product(
      id: 'P005',
      name: 'Baby Carrots Bundle',
      description: 'Sweet, tender baby carrots grown without pesticides. Great for snacking, juicing, or adding colour to your meals.',
      imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&q=80',
      galleryImages: ['https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=800&q=80'],
      pricePerUnit: 14.0,
      unit: 'kg',
      stockQuantity: 180,
      farmerName: 'Kwame Acheampong',
      location: 'Ejisu, Ashanti',
      averageRating: 4.6,
      reviewCount: 73,
      categoryId: 'dummy',
      freshnessLabel: 'Harvested Today',
      isFeatured: true,
      isAvailable: true,
    ),
    Product(
      id: 'P006',
      name: 'Crispy Lettuce Heads',
      description: 'Hydroponic lettuce heads grown locally. Beautifully crisp, washed, and ready to serve. No soil residue.',
      imageUrl: 'https://images.unsplash.com/photo-1556801712-76c9d3e5c51a?w=400&q=80',
      galleryImages: ['https://images.unsplash.com/photo-1556801712-76c9d3e5c51a?w=800&q=80'],
      pricePerUnit: 15.0,
      unit: 'head',
      stockQuantity: 120,
      farmerName: 'Kofi Mensah',
      location: 'Ejisu, Ashanti',
      averageRating: 4.8,
      reviewCount: 42,
      categoryId: 'dummy',
      freshnessLabel: 'Harvested Today',
      isFeatured: true,
      isOnDeal: true,
      originalPrice: 20.0,
      isAvailable: true,
    ),
    Product(
      id: 'P007',
      name: 'Garden Eggs (White)',
      description: 'Traditional white garden eggs, slightly bitter and perfect for stews and egg-plant sauce. A Ghanaian staple.',
      imageUrl: 'https://images.unsplash.com/photo-1618156084-e1e4d6cde41b?w=400&q=80',
      galleryImages: ['https://images.unsplash.com/photo-1618156084-e1e4d6cde41b?w=800&q=80'],
      pricePerUnit: 10.0,
      unit: 'kg',
      stockQuantity: 450,
      farmerName: 'Akua Asante',
      location: 'Mamponteng, Ashanti',
      averageRating: 4.4,
      reviewCount: 96,
      categoryId: 'dummy',
      freshnessLabel: 'Yesterday',
      isAvailable: true,
    ),
    Product(
      id: 'P008',
      name: 'Fresh Green Okra',
      description: 'Tender, stringless okra pods — perfect for okra soup, stir-fries, and grills. Picked at peak tenderness.',
      imageUrl: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&q=80',
      galleryImages: ['https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=800&q=80'],
      pricePerUnit: 20.0,
      unit: 'kg',
      stockQuantity: 220,
      farmerName: 'Ama Boadu',
      location: 'Techiman, B-A Region',
      averageRating: 4.5,
      reviewCount: 61,
      categoryId: 'dummy',
      freshnessLabel: '2 days ago',
      isOnDeal: true,
      originalPrice: 25.0,
      isAvailable: true,
    ),
    Product(
      id: 'P009',
      name: 'Mixed Pepper Bag',
      description: 'A curated mix of green, yellow and red bell peppers plus some bird peppers. Great value for kitchens and restaurants.',
      imageUrl: 'https://images.unsplash.com/photo-1526470498-9ae73c665de8?w=400&q=80',
      galleryImages: ['https://images.unsplash.com/photo-1526470498-9ae73c665de8?w=800&q=80'],
      pricePerUnit: 22.0,
      unit: 'kg',
      stockQuantity: 300,
      farmerName: 'Kwabena Frimpong',
      location: 'Kumasi, Ashanti',
      averageRating: 4.6,
      reviewCount: 115,
      categoryId: 'dummy',
      freshnessLabel: 'Harvested Today',
      isFeatured: true,
      isAvailable: true,
    ),
    Product(
      id: 'P010',
      name: 'Plum Tomatoes (Bulk)',
      description: 'Wholesale plum tomatoes in 10 kg packs. Consistent size and flavour — ideal for restaurants and market vendors.',
      imageUrl: 'https://images.unsplash.com/photo-1561136794-bf44898a4900?w=400&q=80',
      galleryImages: ['https://images.unsplash.com/photo-1561136794-bf44898a4900?w=800&q=80'],
      pricePerUnit: 15.0,
      unit: 'kg',
      stockQuantity: 2000,
      farmerName: 'Yaw Boateng',
      location: 'Agona Swedru, C/R',
      averageRating: 4.2,
      reviewCount: 188,
      categoryId: 'dummy',
      freshnessLabel: 'Yesterday',
      isOnDeal: true,
      originalPrice: 20.0,
      isAvailable: true,
    ),
    Product(
      id: 'P011',
      name: 'Purple Onion (Red)',
      description: 'Vibrant purple-red onions with a mildly sweet, pungent flavour. Preferred for salads, garnishes and grilled dishes.',
      imageUrl: 'https://images.unsplash.com/photo-1618518253167-0d23bed6b2df?w=400&q=80',
      galleryImages: ['https://images.unsplash.com/photo-1618518253167-0d23bed6b2df?w=800&q=80'],
      pricePerUnit: 13.0,
      unit: 'kg',
      stockQuantity: 600,
      farmerName: 'Abena Owusu',
      location: 'Bechem, B-A Region',
      averageRating: 4.3,
      reviewCount: 77,
      categoryId: 'dummy',
      freshnessLabel: '3 days ago',
      isAvailable: true,
    ),
    Product(
      id: 'P012',
      name: 'Sweet Carrot (Large)',
      description: 'Jumbo Nantes carrots — perfectly orange, sweet and crisp. Sourced directly from upland farms for maximum freshness.',
      imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80',
      galleryImages: ['https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80'],
      pricePerUnit: 16.0,
      unit: 'kg',
      stockQuantity: 240,
      farmerName: 'Kwame Acheampong',
      location: 'Ejisu, Ashanti',
      averageRating: 4.7,
      reviewCount: 92,
      categoryId: 'dummy',
      freshnessLabel: 'Harvested Today',
      isFeatured: true,
      isOnDeal: true,
      originalPrice: 20.0,
      isAvailable: true,
    ),
  ];

  static List<Product> get featuredProducts => products.where((p) => p.isFeatured).toList();
  static List<Product> get dealsProducts => products.where((p) => p.isOnDeal).toList();

  static List<Product> productsByCategoryId(String categoryId) =>
      products.where((p) => p.categoryId == categoryId).toList();

  // ─── Reviews ─────────────────────────────────────────────────────────────────

  static final List<ProductReview> sampleReviews = [
    ProductReview(
      id: 'REV001',
      reviewerName: 'Kwame Nkrumah',
      reviewerAvatar: 'https://i.pravatar.cc/50?img=12',
      rating: 5.0,
      comment: 'Extremely fresh! Arrived in perfect condition. Will definitely order again.',
      date: DateTime(2026, 6, 28),
    ),
    ProductReview(
      id: 'REV002',
      reviewerName: 'Adwoa Mensah',
      reviewerAvatar: 'https://i.pravatar.cc/50?img=23',
      rating: 4.5,
      comment: 'Good quality produce. Delivery was on time and packaging was neat.',
      date: DateTime(2026, 6, 25),
    ),
    ProductReview(
      id: 'REV003',
      reviewerName: 'Kojo Anning',
      reviewerAvatar: 'https://i.pravatar.cc/50?img=7',
      rating: 4.0,
      comment: 'Nice tomatoes. A few were slightly bruised but overall great value.',
      date: DateTime(2026, 6, 20),
    ),
  ];

  // ─── Chats ────────────────────────────────────────────────────────────────────

  static final List<ChatConversation> chatConversations = [
    ChatConversation(
      id: 'CHAT001',
      otherUserId: 'FRM001',
      otherUserName: 'Kofi Mensah',
      otherUserAvatar: 'https://i.pravatar.cc/80?img=11',
      isOnline: true,
      lastMessage: 'Yes, I have 200kg of tomatoes available. Would you like a sample first?',
      lastMessageTime: DateTime(2026, 7, 2, 11, 45),
      unreadCount: 2,
      isAgent: false,
    ),
    ChatConversation(
      id: 'CHAT002',
      otherUserId: 'AGT001',
      otherUserName: 'Fredrick Morgan (Agent)',
      otherUserAvatar: 'https://i.pravatar.cc/80?img=33',
      isOnline: true,
      lastMessage: 'Your order #ORD-2026-0834 is on the way. ETA 30 mins.',
      lastMessageTime: DateTime(2026, 7, 2, 12, 30),
      unreadCount: 1,
      isAgent: true,
    ),
    ChatConversation(
      id: 'CHAT003',
      otherUserId: 'FRM002',
      otherUserName: 'Akua Asante',
      otherUserAvatar: 'https://i.pravatar.cc/80?img=5',
      isOnline: false,
      lastMessage: 'Thank you for your order! The peppers will be ready tomorrow.',
      lastMessageTime: DateTime(2026, 7, 1, 16, 20),
      unreadCount: 0,
      isAgent: false,
    ),
    ChatConversation(
      id: 'CHAT004',
      otherUserId: 'FRM007',
      otherUserName: 'Kwabena Frimpong',
      otherUserAvatar: 'https://i.pravatar.cc/80?img=15',
      isOnline: false,
      lastMessage: 'I can offer a bulk discount for 50kg+. Let me know.',
      lastMessageTime: DateTime(2026, 6, 30, 9, 0),
      unreadCount: 0,
      isAgent: false,
    ),
  ];

  static final List<ChatMessage> chatMessages = [
    ChatMessage(
      id: 'MSG001',
      senderId: 'CST001',
      content: 'Hi Kofi, do you have fresh tomatoes available this week?',
      timestamp: DateTime(2026, 7, 2, 11, 30),
      type: MessageType.text,
      isRead: true,
    ),
    ChatMessage(
      id: 'MSG002',
      senderId: 'FRM001',
      content: 'Yes, I have 200kg of tomatoes available. Would you like a sample first?',
      timestamp: DateTime(2026, 7, 2, 11, 45),
      type: MessageType.text,
      isRead: false,
    ),
    ChatMessage(
      id: 'MSG003',
      senderId: 'FRM001',
      content: 'I can also give you a 10% discount for orders above 20kg.',
      timestamp: DateTime(2026, 7, 2, 11, 46),
      type: MessageType.text,
      isRead: false,
    ),
  ];
}
