import 'app_models.dart';

class DummyData {
  DummyData._();

  static final agent = AgentProfile(
    id: 'AGT001',
    name: 'Fredrick Morgan',
    phone: '+233 24 567 8901',
    email: 'f.morgan@soiltech.com',
    agentCode: 'LBC-ASH-001',
    region: 'Ashanti Region',
    district: 'Kumasi Metro',
    avatarUrl: 'https://i.pravatar.cc/150?img=33',
    totalFarmersRegistered: 142,
    totalProduceCollected: 45680,
    totalCollections: 287,
    performanceScore: 94.5,
    joinDate: DateTime(2022, 3, 15),
  );

  static final stats = DashboardStats(
    todayCollections: 7,
    todayFarmers: 5,
    pendingUploads: 3,
    offlineRecords: 2,
    todayWeight: 1842.5,
    weeklyWeight: 12450.0,
    monthlyRevenue: 87340.0,
    activePickups: 4,
  );

  static final List<FarmerModel> farmers = [
    FarmerModel(
      id: 'FRM001',
      name: 'Kofi Mensah',
      phone: '+233 24 123 4567',
      nationalId: 'GHA-12345678-9',
      region: 'Ashanti Region',
      district: 'Ejisu-Juaben',
      community: 'Ejisu',
      avatarUrl: 'https://i.pravatar.cc/150?img=11',
      status: FarmerStatus.active,
      registeredDate: DateTime(2023, 2, 14),
      totalFarms: 2,
      totalAcreage: 8.5,
      farms: [],
      crops: ['Cocoa', 'Plantain'],
      totalCollected: 12450.0,
      syncStatus: SyncStatus.synced,
    ),
    FarmerModel(
      id: 'FRM002',
      name: 'Akua Asante',
      phone: '+233 20 987 6543',
      nationalId: 'GHA-98765432-1',
      region: 'Ashanti Region',
      district: 'Kwabre East',
      community: 'Mamponteng',
      avatarUrl: 'https://i.pravatar.cc/150?img=5',
      status: FarmerStatus.active,
      registeredDate: DateTime(2023, 5, 22),
      totalFarms: 3,
      totalAcreage: 12.0,
      farms: [],
      crops: ['Cocoa', 'Maize', 'Cassava'],
      totalCollected: 18920.0,
      syncStatus: SyncStatus.synced,
    ),
    FarmerModel(
      id: 'FRM003',
      name: 'Yaw Boateng',
      phone: '+233 50 234 5678',
      nationalId: 'GHA-23456789-3',
      region: 'Ashanti Region',
      district: 'Afigya Kwabre',
      community: 'Kuntanase',
      avatarUrl: 'https://i.pravatar.cc/150?img=15',
      status: FarmerStatus.active,
      registeredDate: DateTime(2023, 8, 10),
      totalFarms: 1,
      totalAcreage: 5.0,
      farms: [],
      crops: ['Maize', 'Yam'],
      totalCollected: 7230.0,
      syncStatus: SyncStatus.pending,
    ),
    FarmerModel(
      id: 'FRM004',
      name: 'Abena Owusu',
      phone: '+233 26 345 6789',
      nationalId: 'GHA-34567890-5',
      region: 'Ashanti Region',
      district: 'Bosomtwe',
      community: 'Bonwire',
      avatarUrl: 'https://i.pravatar.cc/150?img=9',
      status: FarmerStatus.active,
      registeredDate: DateTime(2024, 1, 5),
      totalFarms: 2,
      totalAcreage: 9.5,
      farms: [],
      crops: ['Cocoa', 'Cassava'],
      totalCollected: 9870.0,
      syncStatus: SyncStatus.synced,
    ),
    FarmerModel(
      id: 'FRM005',
      name: 'Kwame Acheampong',
      phone: '+233 55 456 7890',
      nationalId: 'GHA-45678901-7',
      region: 'Ashanti Region',
      district: 'Sekyere East',
      community: 'Effiduase',
      avatarUrl: 'https://i.pravatar.cc/150?img=22',
      status: FarmerStatus.inactive,
      registeredDate: DateTime(2022, 11, 30),
      totalFarms: 4,
      totalAcreage: 18.0,
      farms: [],
      crops: ['Cocoa', 'Rice', 'Maize'],
      totalCollected: 31450.0,
      syncStatus: SyncStatus.synced,
    ),
    FarmerModel(
      id: 'FRM006',
      name: 'Ama Serwaa',
      phone: '+233 27 567 8901',
      nationalId: 'GHA-56789012-9',
      region: 'Ashanti Region',
      district: 'Mampong Municipal',
      community: 'Mampong',
      avatarUrl: 'https://i.pravatar.cc/150?img=3',
      status: FarmerStatus.active,
      registeredDate: DateTime(2024, 3, 18),
      totalFarms: 1,
      totalAcreage: 3.5,
      farms: [],
      crops: ['Tomato', 'Pepper'],
      totalCollected: 4120.0,
      syncStatus: SyncStatus.failed,
    ),
    FarmerModel(
      id: 'FRM007',
      name: 'Kwasi Frimpong',
      phone: '+233 24 678 9012',
      nationalId: 'GHA-67890123-1',
      region: 'Ashanti Region',
      district: 'Atwima Nwabiagya',
      community: 'Barekese',
      avatarUrl: 'https://i.pravatar.cc/150?img=19',
      status: FarmerStatus.active,
      registeredDate: DateTime(2023, 6, 25),
      totalFarms: 2,
      totalAcreage: 7.0,
      farms: [],
      crops: ['Cocoa', 'Plantain'],
      totalCollected: 11340.0,
      syncStatus: SyncStatus.synced,
    ),
  ];

  static List<ProduceRecord> get produceRecords => [
    ProduceRecord(
      id: 'PRD001',
      farmerId: 'FRM001',
      farmerName: 'Kofi Mensah',
      farmId: 'FAR001',
      cropType: 'Cocoa',
      weightKg: 420.5,
      quantityBags: 7,
      moisturePercent: 7.2,
      qualityGrade: 'Grade A',
      status: CollectionStatus.approved,
      collectionDate: DateTime.now().subtract(const Duration(hours: 2)),
      photoUrls: [],
      agentId: 'AGT001',
      notes: 'Excellent quality beans, well fermented.',
      pricePerKg: 16.50,
      syncStatus: SyncStatus.synced,
    ),
    ProduceRecord(
      id: 'PRD002',
      farmerId: 'FRM002',
      farmerName: 'Akua Asante',
      farmId: 'FAR002',
      cropType: 'Cocoa',
      weightKg: 285.0,
      quantityBags: 5,
      moisturePercent: 8.1,
      qualityGrade: 'Grade A',
      status: CollectionStatus.submitted,
      collectionDate: DateTime.now().subtract(const Duration(hours: 4)),
      photoUrls: [],
      agentId: 'AGT001',
      notes: 'Good quality, minor moisture concern.',
      pricePerKg: 16.50,
      syncStatus: SyncStatus.synced,
    ),
    ProduceRecord(
      id: 'PRD003',
      farmerId: 'FRM003',
      farmerName: 'Yaw Boateng',
      farmId: 'FAR003',
      cropType: 'Maize',
      weightKg: 650.0,
      quantityBags: 13,
      moisturePercent: 12.5,
      qualityGrade: 'Grade B',
      status: CollectionStatus.draft,
      collectionDate: DateTime.now().subtract(const Duration(hours: 6)),
      photoUrls: [],
      agentId: 'AGT001',
      notes: 'Pending quality verification.',
      pricePerKg: 3.20,
      syncStatus: SyncStatus.pending,
    ),
    ProduceRecord(
      id: 'PRD004',
      farmerId: 'FRM004',
      farmerName: 'Abena Owusu',
      farmId: 'FAR004',
      cropType: 'Cocoa',
      weightKg: 187.5,
      quantityBags: 3,
      moisturePercent: 6.8,
      qualityGrade: 'Grade A',
      status: CollectionStatus.approved,
      collectionDate: DateTime.now().subtract(const Duration(days: 1)),
      photoUrls: [],
      agentId: 'AGT001',
      notes: 'Premium quality.',
      pricePerKg: 16.50,
      syncStatus: SyncStatus.synced,
    ),
    ProduceRecord(
      id: 'PRD005',
      farmerId: 'FRM005',
      farmerName: 'Kwame Acheampong',
      farmId: 'FAR005',
      cropType: 'Rice',
      weightKg: 900.0,
      quantityBags: 18,
      moisturePercent: 14.0,
      qualityGrade: 'Grade B',
      status: CollectionStatus.submitted,
      collectionDate: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
      photoUrls: [],
      agentId: 'AGT001',
      notes: 'Standard grade, good for processing.',
      pricePerKg: 4.80,
      syncStatus: SyncStatus.synced,
    ),
  ];

  static List<PickupRequest> get pickupRequests => [
    PickupRequest(
      id: 'PKP001',
      produceRecordId: 'PRD001',
      farmerId: 'FRM001',
      farmerName: 'Kofi Mensah',
      cropType: 'Cocoa',
      weightKg: 420.5,
      pickupLocation: 'Ejisu Junction, Kumasi',
      pickupLatitude: 6.7157,
      pickupLongitude: -1.4753,
      deliveryLocation: 'SoilTech Warehouse, Kumasi',
      status: LogisticsStatus.inTransit,
      requestDate: DateTime.now().subtract(const Duration(hours: 3)),
      driverName: 'Emmanuel Darko',
      driverPhone: '+233 24 111 2222',
      vehicleNumber: 'AS-3456-22',
      estimatedPickup: DateTime.now().add(const Duration(minutes: 45)),
      syncStatus: SyncStatus.synced,
    ),
    PickupRequest(
      id: 'PKP002',
      produceRecordId: 'PRD002',
      farmerId: 'FRM002',
      farmerName: 'Akua Asante',
      cropType: 'Cocoa',
      weightKg: 285.0,
      pickupLocation: 'Mamponteng Main Road',
      pickupLatitude: 6.7502,
      pickupLongitude: -1.5321,
      deliveryLocation: 'SoilTech Warehouse, Kumasi',
      status: LogisticsStatus.assigned,
      requestDate: DateTime.now().subtract(const Duration(hours: 1)),
      driverName: 'Samuel Asare',
      driverPhone: '+233 20 333 4444',
      vehicleNumber: 'AS-7891-21',
      estimatedPickup: DateTime.now().add(const Duration(hours: 2)),
      syncStatus: SyncStatus.synced,
    ),
    PickupRequest(
      id: 'PKP003',
      produceRecordId: 'PRD003',
      farmerId: 'FRM003',
      farmerName: 'Yaw Boateng',
      cropType: 'Maize',
      weightKg: 650.0,
      pickupLocation: 'Kuntanase Village',
      pickupLatitude: 6.8012,
      pickupLongitude: -1.6123,
      deliveryLocation: 'SoilTech Depot, Ejisu',
      status: LogisticsStatus.pending,
      requestDate: DateTime.now().subtract(const Duration(minutes: 30)),
      syncStatus: SyncStatus.pending,
    ),
    PickupRequest(
      id: 'PKP004',
      produceRecordId: 'PRD004',
      farmerId: 'FRM004',
      farmerName: 'Abena Owusu',
      cropType: 'Cocoa',
      weightKg: 187.5,
      pickupLocation: 'Bonwire Town Center',
      pickupLatitude: 6.7634,
      pickupLongitude: -1.4102,
      deliveryLocation: 'SoilTech Warehouse, Kumasi',
      status: LogisticsStatus.delivered,
      requestDate: DateTime.now().subtract(const Duration(days: 1)),
      driverName: 'Emmanuel Darko',
      driverPhone: '+233 24 111 2222',
      vehicleNumber: 'AS-3456-22',
      estimatedPickup: DateTime.now().subtract(const Duration(hours: 18)),
      syncStatus: SyncStatus.synced,
    ),
  ];

  static List<PaymentRecord> get payments => [
    PaymentRecord(
      id: 'PAY001',
      farmerId: 'FRM001',
      farmerName: 'Kofi Mensah',
      farmerPhone: '+233 24 123 4567',
      produceRecordId: 'PRD001',
      cropType: 'Cocoa',
      amount: 6938.25,
      status: PaymentStatus.pending,
      dueDate: DateTime.now().add(const Duration(days: 2)),
      paymentMethod: 'Mobile Money',
      syncStatus: SyncStatus.synced,
    ),
    PaymentRecord(
      id: 'PAY002',
      farmerId: 'FRM002',
      farmerName: 'Akua Asante',
      farmerPhone: '+233 20 987 6543',
      produceRecordId: 'PRD002',
      cropType: 'Cocoa',
      amount: 4702.50,
      status: PaymentStatus.processing,
      dueDate: DateTime.now().add(const Duration(days: 1)),
      paymentMethod: 'Bank Transfer',
      syncStatus: SyncStatus.synced,
    ),
    PaymentRecord(
      id: 'PAY003',
      farmerId: 'FRM004',
      farmerName: 'Abena Owusu',
      farmerPhone: '+233 26 345 6789',
      produceRecordId: 'PRD004',
      cropType: 'Cocoa',
      amount: 3093.75,
      status: PaymentStatus.paid,
      dueDate: DateTime.now().subtract(const Duration(days: 1)),
      paidDate: DateTime.now().subtract(const Duration(hours: 5)),
      paymentMethod: 'Mobile Money',
      transactionRef: 'MTN-2025-789456',
      syncStatus: SyncStatus.synced,
    ),
    PaymentRecord(
      id: 'PAY004',
      farmerId: 'FRM005',
      farmerName: 'Kwame Acheampong',
      farmerPhone: '+233 55 456 7890',
      produceRecordId: 'PRD005',
      cropType: 'Rice',
      amount: 4320.00,
      status: PaymentStatus.paid,
      dueDate: DateTime.now().subtract(const Duration(days: 2)),
      paidDate: DateTime.now().subtract(const Duration(days: 1)),
      paymentMethod: 'Bank Transfer',
      transactionRef: 'GCB-2025-123789',
      syncStatus: SyncStatus.synced,
    ),
  ];

  static List<AppNotification> get notifications => [
    AppNotification(
      id: 'NOT001',
      title: 'New Price Update',
      body: 'Cocoa Grade A price has been updated to GHS 16.50/kg effective today.',
      type: NotificationType.announcement,
      timestamp: DateTime.now().subtract(const Duration(minutes: 30)),
      isRead: false,
      data: {'type': 'price_update', 'crop': 'Cocoa'},
    ),
    AppNotification(
      id: 'NOT002',
      title: 'Pickup Confirmed',
      body: 'Driver Emmanuel Darko has been assigned to collect from Kofi Mensah.',
      type: NotificationType.task,
      timestamp: DateTime.now().subtract(const Duration(hours: 1)),
      isRead: false,
      data: {'type': 'pickup', 'requestId': 'PKP001'},
    ),
    AppNotification(
      id: 'NOT003',
      title: 'Payment Processed',
      body: 'GHS 3,093.75 has been sent to Abena Owusu via Mobile Money.',
      type: NotificationType.payment,
      timestamp: DateTime.now().subtract(const Duration(hours: 5)),
      isRead: true,
      data: {'type': 'payment', 'paymentId': 'PAY003'},
    ),
    AppNotification(
      id: 'NOT004',
      title: 'Sync Reminder',
      body: 'You have 3 records pending upload. Connect to internet to sync.',
      type: NotificationType.sync,
      timestamp: DateTime.now().subtract(const Duration(hours: 8)),
      isRead: true,
      data: {'type': 'sync', 'count': 3},
    ),
    AppNotification(
      id: 'NOT005',
      title: 'Quality Alert',
      body: 'Record PRD003 needs moisture review before final approval.',
      type: NotificationType.alert,
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      isRead: true,
      data: {'type': 'quality', 'recordId': 'PRD003'},
    ),
    AppNotification(
      id: 'NOT006',
      title: 'Monthly Target Update',
      body: 'You have reached 87% of your monthly collection target. Great work!',
      type: NotificationType.announcement,
      timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 4)),
      isRead: true,
      data: {'type': 'target', 'percent': 87},
    ),
  ];

  static List<Map<String, dynamic>> get weeklyChartData => [
    {'day': 'Mon', 'kg': 1850.0},
    {'day': 'Tue', 'kg': 2340.0},
    {'day': 'Wed', 'kg': 980.0},
    {'day': 'Thu', 'kg': 3120.0},
    {'day': 'Fri', 'kg': 1650.0},
    {'day': 'Sat', 'kg': 2890.0},
    {'day': 'Sun', 'kg': 1620.0},
  ];

  static List<Map<String, dynamic>> get cropDistribution => [
    {'crop': 'Cocoa', 'percent': 0.65, 'kg': 29692.0},
    {'crop': 'Maize', 'percent': 0.15, 'kg': 6852.0},
    {'crop': 'Cassava', 'percent': 0.10, 'kg': 4568.0},
    {'crop': 'Rice', 'percent': 0.07, 'kg': 3198.0},
    {'crop': 'Others', 'percent': 0.03, 'kg': 1370.0},
  ];

  static final List<Map<String, String>> recentActivities = [
    {
      'action': 'Collection recorded',
      'detail': 'Kofi Mensah – 420.5 kg Cocoa',
      'time': '2h ago',
      'icon': 'agriculture',
    },
    {
      'action': 'Farmer registered',
      'detail': 'Akua Asante – Kwabre East',
      'time': '4h ago',
      'icon': 'person_add',
    },
    {
      'action': 'Pickup requested',
      'detail': 'Yaw Boateng – 650 kg Maize',
      'time': '6h ago',
      'icon': 'local_shipping',
    },
    {
      'action': 'Payment sent',
      'detail': 'Abena Owusu – GHS 3,093.75',
      'time': '8h ago',
      'icon': 'payments',
    },
    {
      'action': 'Farm registered',
      'detail': 'Kwame Acheampong – 4.5 acres',
      'time': 'Yesterday',
      'icon': 'terrain',
    },
  ];
}
